//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dersler()
        {
            this.Egitimler = new HashSet<Egitimler>();
        }
    
        public int Dersid { get; set; }
        public string DersAd { get; set; }
        public string Dersicerik { get; set; }
        public string DersDurum { get; set; }
        public int dKatid { get; set; }
        public int dUyeid { get; set; }
        public System.DateTime dyuklenmetarihi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egitimler> Egitimler { get; set; }
    }
}
