//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitimler
    {
        public int Egitimid { get; set; }
        public string Egitimicerik { get; set; }
        public int eUyeid { get; set; }
        public int eDersid { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
